#!/bin/bash

# intialize repository by getting external repos & tools
if [ ! -d "webrepl" ] 
then
	echo "cloning webrepl"
	git clone git@github.com:micropython/webrepl.git
fi

pip install -r requirements.txt
